hooks:
  all:
    pre:
      - type: oidc
        provider: aws
        role_arn: "arn:aws:iam::017777978390:role/terrateam"
destination_branches:
  - branch: "release/*"
  - branch: "main"
    source_branches: ["hotfix/*"]
